"use client";

import Head from "next/head";
import React, { useEffect, useState } from "react";
import Speech from "speak-tts";

interface Greeting {
  german: string;
  bangla: string;
  meaning: string;
}

const greetings: Greeting[] = [
  { german: "Guten Morgen", bangla: "গুটেন মর্গেন", meaning: "Good Morning" },
  { german: "Guten Tag", bangla: "গুটেন টাগ", meaning: "Good Day" },
  { german: "Guten Abend", bangla: "গুটেন আবেন্ড", meaning: "Good Evening" },
  { german: "Gute Nacht", bangla: "গুটে নাখট", meaning: "Good Night" },
  { german: "Hallo", bangla: "হালো", meaning: "Hello" },
  { german: "Tschüss", bangla: "চুস", meaning: "Bye" },
  { german: "Auf Wiedersehen", bangla: "আউফ ভিডারজেন", meaning: "Goodbye" },
  { german: "Wie geht’s?", bangla: "ভি গেটস?", meaning: "How are you?" },
  { german: "Mir geht es gut", bangla: "মিয়ার গেট এস গুট", meaning: "I'm fine" },
  { german: "Danke schön", bangla: "ডাঙ্কে শ্যোন", meaning: "Thank you very much" },
];
export default function Page() {
    const [speech, setSpeech] = useState<Speech | null>(null);

    useEffect(() => {
      const speechInstance = new Speech();
      speechInstance
        .init({
          volume: 1,
          lang: "de-DE",
          rate: 1,
          pitch: 1,
        })
        .then(() => setSpeech(speechInstance))
        .catch((e) => console.error("TTS Error:", e));
    }, []);
  
    const speakGreeting = (text: string) => {
      if (speech) {
        speech.speak({ text });
      }
    };
  
    return (
      <div className="max-w-2xl mx-auto p-6">
        <Head>
            <title>German to Bangla Greetings</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 onClick={() => speakGreeting('Deutsche Grüße')} className="text-2xl font-bold text-center mb-6">German Greetings (Deutsche Grüße  <span className="text-xl cursor-pointer">🔊</span>) 🇩🇪</h1>
  
        <div className="grid grid-cols-1 gap-4">
          {greetings.map((greet, index) => (
            <button
              key={index}
              onClick={() => speakGreeting(greet.german)}
              className="p-4 border border-gray-300 rounded-lg shadow-md flex justify-between items-center
                hover:bg-blue-500 hover:text-white transition-all"
            >
              <div>
                <p className="text-lg font-bold">{index + 1} {greet.german}</p>
                <p className="text-sm text-gray-600">{greet.bangla}</p>
                <p className="text-xs italic">{greet.meaning}</p>
              </div>
              <span className="text-xl">🔊</span>
            </button>
          ))}
        </div>
      </div>
    );
}
